"""Adding index to region. Dropping item.cloud.

Revision ID: 2ce75615b24d
Revises: d08d0b37788a
Create Date: 2016-11-15 20:31:27.393066

"""

# revision identifiers, used by Alembic.
revision = '2ce75615b24d'
down_revision = 'd08d0b37788a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_item_region', 'item', ['region'], unique=False)
    op.drop_column('item', 'cloud')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('cloud', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_index('ix_item_region', table_name='item')
    ### end Alembic commands ###